name: Convert-ASN1
version: 0.20
abstract: Convert between perl data structures and ASN.1 encoded packets
author: Graham Barr <gbarr@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
